# 服务器配置 端口
#server.port=80
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

    username: root
    password: yz
    driver-class-name: com.mysql.cj.jdbc.Driver
